services:
    victoire_core.widget_html_content_resolver:
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Html }

    #alias to the entity
    victoire.widget.html:
        class: Victoire\Widget\HtmlBundle\Entity\WidgetHtml

    #alias to the form
    victoire.widget.form.html:
        class: Victoire\Widget\HtmlBundle\Form\WidgetHtmlType
        tags:
            - { name: form.type }
